// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7iMwkoFLCqw9tR57CGgnjsWL3v__Bd2A',
    appId: '1:655378037816:web:4dad8950721d06d0133acd',
    messagingSenderId: '655378037816',
    projectId: 'talabat-pro-f788d',
    authDomain: 'talabat-pro-f788d.firebaseapp.com',
    storageBucket: 'talabat-pro-f788d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIPb32gHNf6e1dHHn8vC3LZu8ZYmRavK0',
    appId: '1:655378037816:android:d97a2750072d67da133acd',
    messagingSenderId: '655378037816',
    projectId: 'talabat-pro-f788d',
    storageBucket: 'talabat-pro-f788d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkFacnf1YD7LDhTsxrvKVnEz4oLIAiOJY',
    appId: '1:655378037816:ios:fb5391ff26490db9133acd',
    messagingSenderId: '655378037816',
    projectId: 'talabat-pro-f788d',
    storageBucket: 'talabat-pro-f788d.firebasestorage.app',
    iosBundleId: 'com.example.talabatpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkFacnf1YD7LDhTsxrvKVnEz4oLIAiOJY',
    appId: '1:655378037816:ios:fb5391ff26490db9133acd',
    messagingSenderId: '655378037816',
    projectId: 'talabat-pro-f788d',
    storageBucket: 'talabat-pro-f788d.firebasestorage.app',
    iosBundleId: 'com.example.talabatpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7iMwkoFLCqw9tR57CGgnjsWL3v__Bd2A',
    appId: '1:655378037816:web:3fd85d74f87003e2133acd',
    messagingSenderId: '655378037816',
    projectId: 'talabat-pro-f788d',
    authDomain: 'talabat-pro-f788d.firebaseapp.com',
    storageBucket: 'talabat-pro-f788d.firebasestorage.app',
  );
}
